# Generated by Django 5.1.4 on 2024-12-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='user_photos/default.jpg', null=True, upload_to='user_photos/', verbose_name='Profile Photo'),
        ),
    ]
