# Generated by Django 5.1.4 on 2024-12-31 17:43

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/', validators=[comments.models.validate_file_extension, comments.models.validate_file_size], verbose_name='Attached File'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', validators=[comments.models.validate_image_size], verbose_name='Attached Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_files/', validators=[comments.models.validate_file_extension, comments.models.validate_file_size], verbose_name='Attached File'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[comments.models.validate_image_size], verbose_name='Attached Image'),
        ),
    ]
